# Generated by Django 2.0.5 on 2018-05-07 03:34

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180503_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner_photo',
            field=versatileimagefield.fields.VersatileImageField(upload_to='static/media', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
