# Generated by Django 2.0.5 on 2018-05-09 05:41

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180507_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog',
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=120, validators=[blog.models.validate_tag_name]),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
